### ISSUE TITLE
Ensure no negative prices?

### ISSUE THREAD

**Issue by prakharmehta95** [prakharmehta95/commsolar#12]
https://github.com/prakharmehta95/commsolar/blob/114257609d526d3daea31abf76a2a4866de220cc/code/COSA_Agent/BuildingAgent.py#L1296

Hi @anunezji 
Just wondering if you checked before that here there are no negative prices because of the subtraction terms.

**Comment by anunezji** [comment]
I have not checked tihs.

However, since the electricity tariffs are assigned based on annual electricity demand and building use, and electricity prices always decrease from one tariff for smaller to larger consumers, I think we should never see negative prices here.

**Comment by anunezji** [comment]
Thinking about it. If the result is negative, it would be relevant because it indicates that the potential adopters will have to pay more for the electricity they still have to consume from the grid. Hence, I think it is best to keep this is as it is.
