### ISSUE TITLE
Unnecessary space here, might give errors

### ISSUE THREAD

**Issue by prakharmehta95** [prakharmehta95/commsolar#5]
https://github.com/prakharmehta95/commsolar/blob/b65ba6a4a902b9416152d14f185fb188217ed256/code/COSA_Model/SolarAdoptionModel.py#L312

**Comment by anunezji** [comment]
Thanks for mentioning this!

On my local code (open with VS Code), there is no space so I guess this is a small appearance bug with the GitHub version. On my editor, I have a ruler that limits the number of characters per line and breaks the line automatically when reached. This may be the cause of this issue.

![2020-12-15 16_38_17-SolarAdoptionModel py - Visual Studio Code](https://user-images.githubusercontent.com/18244912/102236704-19292000-3ef4-11eb-90b2-435352662ce4.png)
