### ISSUE TITLE
Only active agent being checked

### ISSUE THREAD

**Issue by prakharmehta95** [prakharmehta95/commsolar#8]
https://github.com/prakharmehta95/commsolar/blob/114257609d526d3daea31abf76a2a4866de220cc/code/COSA_Agent/BuildingAgent.py#L512

Here only active agent is being checked, so the members_decision list is basically appended only for the active agent. The list contains only one element.

So decision made only by active agent, other agents are not included. 

Here we can introduce a comparison for each agent to their individual NPV, so they only accept if NPV share is better than individual NPV.

**Comment by anunezji** [comment]
No, because ag refers to a `for` that goes over the object instances in the list of building members:
`for ag in c_max_npv_dict["members"]:`

(see line 506 of referenced script)
